# Generated by Django 3.1.1 on 2020-09-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StartUpApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialinvestment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_investment_details', to='StartUpApi.investorinformation'),
        ),
    ]
