# Generated by Django 3.1.1 on 2020-09-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartUpApi', '0002_auto_20200910_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinformation',
            name='email_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investorinformation',
            name='mobile_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investorinformation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investorinformation',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investorinformation',
            name='company_invested',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investorinformation',
            name='year_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
