# Generated by Django 3.1.1 on 2020-09-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartUpApi', '0004_auto_20200911_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorinformation',
            name='company_invested',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investorinformation',
            name='year_of_experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
