# Generated by Django 3.1.1 on 2020-09-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StartUpApi', '0005_auto_20200911_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentdetail',
            old_name='investor_company_relaion',
            new_name='investor_company_relation',
        ),
    ]
