# Generated by Django 3.1.1 on 2020-09-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StartUpApi', '0006_auto_20200911_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorposition',
            old_name='investor_position',
            new_name='position',
        ),
    ]
